# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Study\University\Y1T2\Python\music\PyQt-Fluent-Widgets\designerDemo\demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1066, 702)
        self.LineEdit = LineEdit(Form)
        self.LineEdit.setGeometry(QtCore.QRect(610, 400, 128, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.SearchLineEdit = SearchLineEdit(Form)
        self.SearchLineEdit.setGeometry(QtCore.QRect(620, 160, 187, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.SwitchButton = SwitchButton(Form)
        self.SwitchButton.setGeometry(QtCore.QRect(920, 40, 76, 37))
        self.SwitchButton.setObjectName("SwitchButton")
        self.ProgressBar = ProgressBar(Form)
        self.ProgressBar.setGeometry(QtCore.QRect(630, 330, 87, 4))
        self.ProgressBar.setVal(0.0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NavigationInterface = NavigationInterface(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavigationInterface.sizePolicy().hasHeightForWidth())
        self.NavigationInterface.setSizePolicy(sizePolicy)
        self.NavigationInterface.setObjectName("NavigationInterface")
        self.verticalLayout.addWidget(self.NavigationInterface)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SearchLineEdit.setText(_translate("Form", "Search"))
from qfluentwidgets import LineEdit, NavigationInterface, ProgressBar, SearchLineEdit, SwitchButton
